application: vod-ventana-educativa
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: css
- url: /imagenes
  static_dir: imagenes
- url: /js
  static_dir: js

- url: /serie
  script: vod/serie.php
- url: /(.+)
  script: \1.php
- url: /
  script: vod/index.php


